### ISSUE TITLE
Swap counterclockwise for clockwise default

### ISSUE THREAD

**Issue by tmcw** [mapbox/geojson-rewind#1]

**Comment by Fil** [comment]
You might want to change this in the CLI too — currently to get a clockwise geometry (compatible with D3) you need to call

`geojson-rewind --counterclockwise original.geojson > cw.geojson`

which is kinda counter-intuitive 🤣

Full example:

```
# download
curl https://pastebin.com/raw/j5MN7AjA > ./original.geojson

# follows GeoJSON spec
geojson-rewind original.geojson > ccw.geojson
# this won't work: D3 expects clockwise polygons
geoproject 'd3.geoTransverseMercator().fitSize([960, 500], d)' < ccw.geojson > ccw-projected.json
geo2svg --fill red ccw-projected.json > ccw.svg

# d3-compatible
# note that the --counterclockwise option creates clockwise polygons 
geojson-rewind --counterclockwise original.geojson > cw.geojson
geoproject 'd3.geoTransverseMercator().fitSize([960, 500], d)' < cw.geojson > cw-projected.json
geo2svg --fill green cw-projected.json > cw.svg
```


Ref: https://gis.stackexchange.com/questions/348120/scale-and-fit-geojson-to-the-svg-map-with-d3-geo

(Triple checked, but still possible that I'm the one who's mixed up.)

**Comment by jgravois** [comment]
> You might want to change this in the CLI too

see https://github.com/mapbox/geojson-rewind/pull/9
