### ISSUE TITLE
Does not rewind GeometryCollections

### ISSUE THREAD

**Issue by gmaclennan** [mapbox/geojson-rewind#13]
They just get ignored.

**Comment by rocky1138** [comment]
I saw that the work was done on this a little while ago but it never got merged in due to some conflicts. I resolved them and created a new PR here: https://github.com/mapbox/geojson-rewind/pull/20. Don't mean to step on anyone's toes!

**Comment by gmaclennan** [comment]
Thanks @rocky1138, I’d forgotten about this.

**Comment by andrewharvey** [comment]
@gmaclennan looks like this is fixed now in the latest `@mapbox/geojson-rewind`, want to close this ticket?

**Comment by gmaclennan** [comment]
👍
