### ISSUE TITLE
Doesn't handle near-zero-area polygons properly

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/geojson-rewind#21]
Hi there! I've got a set of polygons that I cannot rewind with `geojson-rewind`.

GeoJSON: https://gist.github.com/stepankuzmin/f12965a84eee3eed6df89e65d48696ae

Steps to reproduce:

```js
const fs = require('fs');
const geojsonhint = require('@mapbox/geojsonhint');
const rewind = require('geojson-rewind');

const geojson = JSON.parse(fs.readFileSync('./invalid.geojson'));
const errors = geojsonhint.hint(geojson);
console.log(errors[0].message); // Polygons and MultiPolygons should follow the right-hand rule

const rewindedGeojson = rewind(geojson);
const newErrors = geojsonhint.hint(rewindedGeojson);
console.log(newErrors[0].message); // Polygons and MultiPolygons should follow the right-hand rule
```

`geojson-rewind` `0.3.1` and `github:mapbox/geojson-rewind#v0.4.0`
`@mapbox/geojsonhint` `2.1.0`

**Comment by krisaoe** [comment]
Same issue here. Did you mangage to resolve this @stepankuzmin ?

**Comment by stepankuzmin** [comment]
Nope ¯\_(ツ)_/¯

**Comment by krisaoe** [comment]
No matter what I tried with this package, identical geojson is returned.
@stepankuzmin  I ended up using @turf/rewind, works like a charm.

**Comment by hoogw** [comment]
> No matter what I tried with this package, identical geojson is returned.
> @stepankuzmin I ended up using @turf/rewind, works like a charm.

Same here, no matter what polygon I input, use false, or true, the result always is same as orginal input, rewind did not work.

**Comment by hoogw** [comment]
@turf/rewind, works like a charm, but not solve my problem. 

                          // https://macwright.org/2016/09/26/the-180th-meridian.html




                          // geojson must follow right hand rule, means must counter-clock-wise, 
                          // if user zoom to the whole world, or alaska area,   bounding box will cross the 180th meridian, will get error validate with geojsonlint ( not counter clock wise error)
                          // so must re-winding the geojson points,  normally, it is 01234(sw, se, ne, nw),  re-winding means, 03214( swtich 3 and 1)
                          // this will create another polgyon cross the other side of earth( asia), not the one we need cross 180th meridian. (rewind is not the solution)


                                            // rewind, not use, but tried 
                                            // NOT works,  https://github.com/mapbox/geojson-rewind,  no matter what polygon I input, alway output the same, no rewind
                                            
                                            // works @turf/rewind  https://github.com/Turfjs/turf/tree/master/packages/turf-rewind
                                            //  var original_polygon = turf.polygon(current_bounding_box.coordinates);
                                            //  var rewind_polygon = turf.rewind(original_polygon, { reverse:false,  mutate: false });   // default reverse:false, mutate:false


                         // 2 way:
                         //  one way, create 2 polygon, split by 180 meridian ( geojson recommended, but may be hard for software to implement)
                         //  second way, 360-(+178) = -(182), use number outside range -180 to +180. ( easy for software implement )  

                         // how to identify if geojson cross 180 meridian? geojonhint()
                         var geojsonhint_error = geojsonhint.hint(current_bounding_box,  {noDuplicateMembers: false })

**Comment by mourner** [comment]
In this case the problem is caused by a few polygons in the test example that look like this:

```
[
    [7.396768398983337, 43.72260793482001],
    [7.396784857564814, 43.722607191112004],
    [7.396784857564812, 43.722607191112004],
    [7.396768398983337, 43.72260793482001]
]
```

Due to floating point error, calculating an area of a near-zero area polygon produces 0, even if you reverse the order of the point. I can fix this on `geojson-rewind` side with a [more precise summation algorithm](https://github.com/mapbox/geojson-rewind/commit/80bb3e9139f7078feabf4afaa860bd57bef575cb), but to update the tests, we would need a fix on `geojsonhint` side as well because it has the same issue.
