### ISSUE TITLE
Possible error in rewindRing error calculation

### ISSUE THREAD

**Issue by chuckwondo** [mapbox/geojson-rewind#34]
In the `rewindRing` function, the following line exists:

```javascript
err += Math.abs(area) >= Math.abs(k) ? area - m + k : k - m + area;
```

I'm not familiar enough with the domain-specific calculations, but from a purely mathematical standpoint, the following computations are equivalent, regardless of the relative absolute values of `area` and `k`:

```javascript
area - m + k
k - m + area
```

I don't know if one of those expressions is incorrect, and thus should be fixed, or if the comparison of absolute values can simply be eliminated and either computation can always be used.

**Comment by mourner** [comment]
It's intentional — the results can be slightly different because of floating point errors. See https://en.wikipedia.org/wiki/Kahan_summation_algorithm (and the Kahan–Babuška algorithm this comes from).

**Comment by chuckwondo** [comment]
Ah. Thanks for the clarification. Consider adding that link in a comment for that function.
